api_platform:
    graphql:
        graphiql:
            enabled: false
    eager_loading:
        max_joins: 2000
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Hello API Platform
    version: 1.0.0
    # Enable the Varnish integration
#    http_cache:
#        invalidation:
#            enabled: false
#            varnish_urls: ['%env(VARNISH_URL)%']
#        max_age: 0
#        shared_max_age: 1
#        vary: ['Content-Type', 'Authorization']
#        public: true
